server:
  port: 8080
  servlet:
    context-path: /jms

spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp

  datasource:
    url: jdbc:sqlserver://localhost:1433;databasename=db_jobManagementSystem
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: jms_admin
    password: 123456

  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

mybatis:
  type-aliases-package: com.gxun.jms.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
